In [16]:
from scipy.io import arff
import pandas as pd

# filename = 'Parkinson_withoutdupl_20_v02.arff'
filename = 'HeartDisease_withoutdupl_02_v09.arff'
folder = 'HeartDisease'

data = arff.loadarff('datasets/{}/{}'.format(folder, filename))
df = pd.DataFrame(data[0])
df.columns = [x.replace(':', '_') for x in df.columns]
df.columns = [x.replace('(', '_') for x in df.columns]
df.columns = [x.replace(')', '') for x in df.columns]
df.columns = [x.replace('%', 'Percent') for x in df.columns]

df.head()

,Age,Sex,ChestPainType,RestBloodPressure,SerumCholestoral,FastingBloodSugar,ResElectrocardiographic,MaxHeartRate,ExerciseInduced,Oldpeak,Slope,MajorVessels,Thal,id,outlier
0,43.0,0.0,4.0,132.0,341.0,1.0,2.0,136.0,1.0,3.0,2.0,0.0,7.0,228.0,"b""'yes'"""
1,70.0,1.0,3.0,160.0,269.0,0.0,0.0,112.0,1.0,29.0,2.0,1.0,7.0,190.0,"b""'yes'"""
2,56.0,0.0,4.0,134.0,409.0,0.0,2.0,150.0,1.0,19.0,2.0,2.0,7.0,182.0,"b""'yes'"""
3,67.0,0.0,3.0,115.0,564.0,0.0,2.0,160.0,0.0,16.0,2.0,0.0,7.0,2.0,"b""'no'"""
4,64.0,1.0,4.0,128.0,263.0,0.0,0.0,105.0,1.0,2.0,2.0,1.0,7.0,4.0,"b""'no'"""

In [17]:
df.to_csv('datasets/{}'.format(filename.replace('arff', 'csv')), index_label='Index')